//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierPortalService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TEST1\\SQLEXPRESS;Initial Catalog=CLS_Workflow;Integrated Security=Tru" +
            "e")]
        public string connectionStr01 {
            get {
                return ((string)(this["connectionStr01"]));
            }
            set {
                this["connectionStr01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr02 {
            get {
                return ((string)(this["connectionStr02"]));
            }
            set {
                this["connectionStr02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr03 {
            get {
                return ((string)(this["connectionStr03"]));
            }
            set {
                this["connectionStr03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr04 {
            get {
                return ((string)(this["connectionStr04"]));
            }
            set {
                this["connectionStr04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr05 {
            get {
                return ((string)(this["connectionStr05"]));
            }
            set {
                this["connectionStr05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr06 {
            get {
                return ((string)(this["connectionStr06"]));
            }
            set {
                this["connectionStr06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr07 {
            get {
                return ((string)(this["connectionStr07"]));
            }
            set {
                this["connectionStr07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr08 {
            get {
                return ((string)(this["connectionStr08"]));
            }
            set {
                this["connectionStr08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr09 {
            get {
                return ((string)(this["connectionStr09"]));
            }
            set {
                this["connectionStr09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string connectionStr10 {
            get {
                return ((string)(this["connectionStr10"]));
            }
            set {
                this["connectionStr10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string interval {
            get {
                return ((string)(this["interval"]));
            }
            set {
                this["interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp.doksend.com")]
        public string portalFilesRouteKey {
            get {
                return ((string)(this["portalFilesRouteKey"]));
            }
            set {
                this["portalFilesRouteKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLS_Workflow=speedyservices.com|topimagesystems.com")]
        public string app01WhoCanSeeInPortal {
            get {
                return ((string)(this["app01WhoCanSeeInPortal"]));
            }
            set {
                this["app01WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app02WhoCanSeeInPortal {
            get {
                return ((string)(this["app02WhoCanSeeInPortal"]));
            }
            set {
                this["app02WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app03WhoCanSeeInPortal {
            get {
                return ((string)(this["app03WhoCanSeeInPortal"]));
            }
            set {
                this["app03WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app04WhoCanSeeInPortal {
            get {
                return ((string)(this["app04WhoCanSeeInPortal"]));
            }
            set {
                this["app04WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app05WhoCanSeeInPortal {
            get {
                return ((string)(this["app05WhoCanSeeInPortal"]));
            }
            set {
                this["app05WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app06WhoCanSeeInPortal {
            get {
                return ((string)(this["app06WhoCanSeeInPortal"]));
            }
            set {
                this["app06WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app07WhoCanSeeInPortal {
            get {
                return ((string)(this["app07WhoCanSeeInPortal"]));
            }
            set {
                this["app07WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app08WhoCanSeeInPortal {
            get {
                return ((string)(this["app08WhoCanSeeInPortal"]));
            }
            set {
                this["app08WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app09WhoCanSeeInPortal {
            get {
                return ((string)(this["app09WhoCanSeeInPortal"]));
            }
            set {
                this["app09WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app10WhoCanSeeInPortal {
            get {
                return ((string)(this["app10WhoCanSeeInPortal"]));
            }
            set {
                this["app10WhoCanSeeInPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\cls")]
        public string app01ImportPath {
            get {
                return ((string)(this["app01ImportPath"]));
            }
            set {
                this["app01ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app02ImportPath {
            get {
                return ((string)(this["app02ImportPath"]));
            }
            set {
                this["app02ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app03ImportPath {
            get {
                return ((string)(this["app03ImportPath"]));
            }
            set {
                this["app03ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app04ImportPath {
            get {
                return ((string)(this["app04ImportPath"]));
            }
            set {
                this["app04ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app05ImportPath {
            get {
                return ((string)(this["app05ImportPath"]));
            }
            set {
                this["app05ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app06ImportPath {
            get {
                return ((string)(this["app06ImportPath"]));
            }
            set {
                this["app06ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app07ImportPath {
            get {
                return ((string)(this["app07ImportPath"]));
            }
            set {
                this["app07ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app08ImportPath {
            get {
                return ((string)(this["app08ImportPath"]));
            }
            set {
                this["app08ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app09ImportPath {
            get {
                return ((string)(this["app09ImportPath"]));
            }
            set {
                this["app09ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string app10ImportPath {
            get {
                return ((string)(this["app10ImportPath"]));
            }
            set {
                this["app10ImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Name")]
        public string fieldIRSupplierName {
            get {
                return ((string)(this["fieldIRSupplierName"]));
            }
            set {
                this["fieldIRSupplierName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Street")]
        public string fieldIRSupplierStreet {
            get {
                return ((string)(this["fieldIRSupplierStreet"]));
            }
            set {
                this["fieldIRSupplierStreet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_ZIP")]
        public string fieldIRSupplierZIP {
            get {
                return ((string)(this["fieldIRSupplierZIP"]));
            }
            set {
                this["fieldIRSupplierZIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_City")]
        public string fieldIRSupplier_City {
            get {
                return ((string)(this["fieldIRSupplier_City"]));
            }
            set {
                this["fieldIRSupplier_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_VATID")]
        public string fieldIRSupplier_VATID {
            get {
                return ((string)(this["fieldIRSupplier_VATID"]));
            }
            set {
                this["fieldIRSupplier_VATID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Postbox")]
        public string fieldIRSupplier_Postbox {
            get {
                return ((string)(this["fieldIRSupplier_Postbox"]));
            }
            set {
                this["fieldIRSupplier_Postbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Postbox_City")]
        public string fieldIRSupplier_Postbox_City {
            get {
                return ((string)(this["fieldIRSupplier_Postbox_City"]));
            }
            set {
                this["fieldIRSupplier_Postbox_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Postbox_Zip")]
        public string fieldIRSupplier_Postbox_Zip {
            get {
                return ((string)(this["fieldIRSupplier_Postbox_Zip"]));
            }
            set {
                this["fieldIRSupplier_Postbox_Zip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Telephone1")]
        public string fieldIRSupplier_Telephone1 {
            get {
                return ((string)(this["fieldIRSupplier_Telephone1"]));
            }
            set {
                this["fieldIRSupplier_Telephone1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Telephone2")]
        public string fieldIRSupplier_Telephone2 {
            get {
                return ((string)(this["fieldIRSupplier_Telephone2"]));
            }
            set {
                this["fieldIRSupplier_Telephone2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Faxnumber")]
        public string fieldIRSupplier_Faxnumber {
            get {
                return ((string)(this["fieldIRSupplier_Faxnumber"]));
            }
            set {
                this["fieldIRSupplier_Faxnumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_SWIFT")]
        public string fieldIRSupplier_SWIFT {
            get {
                return ((string)(this["fieldIRSupplier_SWIFT"]));
            }
            set {
                this["fieldIRSupplier_SWIFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_IBAN")]
        public string fieldIRSupplier_IBAN {
            get {
                return ((string)(this["fieldIRSupplier_IBAN"]));
            }
            set {
                this["fieldIRSupplier_IBAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_IBAN2")]
        public string fieldIRSupplier_IBAN2 {
            get {
                return ((string)(this["fieldIRSupplier_IBAN2"]));
            }
            set {
                this["fieldIRSupplier_IBAN2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Branchcode")]
        public string fieldIRSupplier_Branchcode {
            get {
                return ((string)(this["fieldIRSupplier_Branchcode"]));
            }
            set {
                this["fieldIRSupplier_Branchcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Branchcode2")]
        public string fieldIRSupplier_Branchcode2 {
            get {
                return ((string)(this["fieldIRSupplier_Branchcode2"]));
            }
            set {
                this["fieldIRSupplier_Branchcode2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_Branchcode3")]
        public string fieldIRSupplier_Branchcode3 {
            get {
                return ((string)(this["fieldIRSupplier_Branchcode3"]));
            }
            set {
                this["fieldIRSupplier_Branchcode3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_AccountNo")]
        public string fieldIRSupplier_AccountNo {
            get {
                return ((string)(this["fieldIRSupplier_AccountNo"]));
            }
            set {
                this["fieldIRSupplier_AccountNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_AccountNo2")]
        public string fieldIRSupplier_AccountNo2 {
            get {
                return ((string)(this["fieldIRSupplier_AccountNo2"]));
            }
            set {
                this["fieldIRSupplier_AccountNo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_AccountNo3")]
        public string fieldIRSupplier_AccountNo3 {
            get {
                return ((string)(this["fieldIRSupplier_AccountNo3"]));
            }
            set {
                this["fieldIRSupplier_AccountNo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Document_Type")]
        public string fieldIRDocument_Type {
            get {
                return ((string)(this["fieldIRDocument_Type"]));
            }
            set {
                this["fieldIRDocument_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invoice_Number")]
        public string fieldIRInvoice_Number {
            get {
                return ((string)(this["fieldIRInvoice_Number"]));
            }
            set {
                this["fieldIRInvoice_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeliveryNoteNo")]
        public string fieldIRDeliveryNoteNo {
            get {
                return ((string)(this["fieldIRDeliveryNoteNo"]));
            }
            set {
                this["fieldIRDeliveryNoteNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SupplierTaxNo")]
        public string fieldIRSupplierTaxNo {
            get {
                return ((string)(this["fieldIRSupplierTaxNo"]));
            }
            set {
                this["fieldIRSupplierTaxNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SupplierEsrNo")]
        public string fieldIRSupplierEsrNo {
            get {
                return ((string)(this["fieldIRSupplierEsrNo"]));
            }
            set {
                this["fieldIRSupplierEsrNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SupplierEsrAccount")]
        public string fieldIRSupplierEsrAccount {
            get {
                return ((string)(this["fieldIRSupplierEsrAccount"]));
            }
            set {
                this["fieldIRSupplierEsrAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_Name")]
        public string fieldIRReceiver_Name {
            get {
                return ((string)(this["fieldIRReceiver_Name"]));
            }
            set {
                this["fieldIRReceiver_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_Street")]
        public string fieldIRReceiver_Street {
            get {
                return ((string)(this["fieldIRReceiver_Street"]));
            }
            set {
                this["fieldIRReceiver_Street"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_ZIP")]
        public string fieldIRReceiver_ZIP {
            get {
                return ((string)(this["fieldIRReceiver_ZIP"]));
            }
            set {
                this["fieldIRReceiver_ZIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_City")]
        public string fieldIRReceiver_City {
            get {
                return ((string)(this["fieldIRReceiver_City"]));
            }
            set {
                this["fieldIRReceiver_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_VATID")]
        public string fieldIRReceiver_VATID {
            get {
                return ((string)(this["fieldIRReceiver_VATID"]));
            }
            set {
                this["fieldIRReceiver_VATID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Net_Amount1")]
        public string fieldIRNet_Amount1 {
            get {
                return ((string)(this["fieldIRNet_Amount1"]));
            }
            set {
                this["fieldIRNet_Amount1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT1")]
        public string fieldIRVAT1 {
            get {
                return ((string)(this["fieldIRVAT1"]));
            }
            set {
                this["fieldIRVAT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT_Amount1")]
        public string fieldIRVAT_Amount1 {
            get {
                return ((string)(this["fieldIRVAT_Amount1"]));
            }
            set {
                this["fieldIRVAT_Amount1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Net_Amount2")]
        public string fieldIRNet_Amount2 {
            get {
                return ((string)(this["fieldIRNet_Amount2"]));
            }
            set {
                this["fieldIRNet_Amount2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT2")]
        public string fieldIRVAT2 {
            get {
                return ((string)(this["fieldIRVAT2"]));
            }
            set {
                this["fieldIRVAT2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT_Amount2")]
        public string fieldIRVAT_Amount2 {
            get {
                return ((string)(this["fieldIRVAT_Amount2"]));
            }
            set {
                this["fieldIRVAT_Amount2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other_Costs1")]
        public string fieldIROther_Costs1 {
            get {
                return ((string)(this["fieldIROther_Costs1"]));
            }
            set {
                this["fieldIROther_Costs1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other_Costs2")]
        public string fieldIROther_Costs2 {
            get {
                return ((string)(this["fieldIROther_Costs2"]));
            }
            set {
                this["fieldIROther_Costs2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other_Costs3")]
        public string fieldIROther_Costs3 {
            get {
                return ((string)(this["fieldIROther_Costs3"]));
            }
            set {
                this["fieldIROther_Costs3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other_Costs4")]
        public string fieldIROther_Costs4 {
            get {
                return ((string)(this["fieldIROther_Costs4"]));
            }
            set {
                this["fieldIROther_Costs4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discount")]
        public string fieldIRDiscount {
            get {
                return ((string)(this["fieldIRDiscount"]));
            }
            set {
                this["fieldIRDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Total_Amount")]
        public string fieldIRTotal_Amount {
            get {
                return ((string)(this["fieldIRTotal_Amount"]));
            }
            set {
                this["fieldIRTotal_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Currency")]
        public string fieldIRCurrency {
            get {
                return ((string)(this["fieldIRCurrency"]));
            }
            set {
                this["fieldIRCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PO_Number")]
        public string fieldIRPO_Number {
            get {
                return ((string)(this["fieldIRPO_Number"]));
            }
            set {
                this["fieldIRPO_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUKRS")]
        public string fieldIRBUKRS {
            get {
                return ((string)(this["fieldIRBUKRS"]));
            }
            set {
                this["fieldIRBUKRS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScanDate")]
        public string fieldIRScanDate {
            get {
                return ((string)(this["fieldIRScanDate"]));
            }
            set {
                this["fieldIRScanDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invoice_Date")]
        public string fieldIRInvoice_Date {
            get {
                return ((string)(this["fieldIRInvoice_Date"]));
            }
            set {
                this["fieldIRInvoice_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceType")]
        public string fieldIRInvoiceType {
            get {
                return ((string)(this["fieldIRInvoiceType"]));
            }
            set {
                this["fieldIRInvoiceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Net_Amount3")]
        public string fieldIRNet_Amount3 {
            get {
                return ((string)(this["fieldIRNet_Amount3"]));
            }
            set {
                this["fieldIRNet_Amount3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Net_Amount4")]
        public string fieldIRNet_Amount4 {
            get {
                return ((string)(this["fieldIRNet_Amount4"]));
            }
            set {
                this["fieldIRNet_Amount4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT3")]
        public string fieldIRVAT3 {
            get {
                return ((string)(this["fieldIRVAT3"]));
            }
            set {
                this["fieldIRVAT3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT4")]
        public string fieldIRVAT4 {
            get {
                return ((string)(this["fieldIRVAT4"]));
            }
            set {
                this["fieldIRVAT4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT_Amount3")]
        public string fieldIRVAT_Amount3 {
            get {
                return ((string)(this["fieldIRVAT_Amount3"]));
            }
            set {
                this["fieldIRVAT_Amount3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VAT_Amount4")]
        public string fieldIRVAT_Amount4 {
            get {
                return ((string)(this["fieldIRVAT_Amount4"]));
            }
            set {
                this["fieldIRVAT_Amount4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BatchId")]
        public string fieldIRBatchId {
            get {
                return ((string)(this["fieldIRBatchId"]));
            }
            set {
                this["fieldIRBatchId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client")]
        public string fieldIRClient {
            get {
                return ((string)(this["fieldIRClient"]));
            }
            set {
                this["fieldIRClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Memo")]
        public string fieldIRMemo {
            get {
                return ((string)(this["fieldIRMemo"]));
            }
            set {
                this["fieldIRMemo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_BankdataMatched")]
        public string fieldIRSupplier_BankdataMatched {
            get {
                return ((string)(this["fieldIRSupplier_BankdataMatched"]));
            }
            set {
                this["fieldIRSupplier_BankdataMatched"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CompletionUser")]
        public string fieldIRCompletionUser {
            get {
                return ((string)(this["fieldIRCompletionUser"]));
            }
            set {
                this["fieldIRCompletionUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OCRState")]
        public string fieldIROCRState {
            get {
                return ((string)(this["fieldIROCRState"]));
            }
            set {
                this["fieldIROCRState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SeperationBarcode")]
        public string fieldIRSeperationBarcode {
            get {
                return ((string)(this["fieldIRSeperationBarcode"]));
            }
            set {
                this["fieldIRSeperationBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discount_Amount")]
        public string fieldIRDiscount_Amount {
            get {
                return ((string)(this["fieldIRDiscount_Amount"]));
            }
            set {
                this["fieldIRDiscount_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ext_1")]
        public string fieldIRExt_1 {
            get {
                return ((string)(this["fieldIRExt_1"]));
            }
            set {
                this["fieldIRExt_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ext_2")]
        public string fieldIRExt_2 {
            get {
                return ((string)(this["fieldIRExt_2"]));
            }
            set {
                this["fieldIRExt_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ext_3")]
        public string fieldIRExt_3 {
            get {
                return ((string)(this["fieldIRExt_3"]));
            }
            set {
                this["fieldIRExt_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_NameRow2")]
        public string fieldIRReceiver_NameRow2 {
            get {
                return ((string)(this["fieldIRReceiver_NameRow2"]));
            }
            set {
                this["fieldIRReceiver_NameRow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeliveryDateFrom")]
        public string fieldIRDeliveryDateFrom {
            get {
                return ((string)(this["fieldIRDeliveryDateFrom"]));
            }
            set {
                this["fieldIRDeliveryDateFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeliveryDateTo")]
        public string fieldIRDeliveryDateTo {
            get {
                return ((string)(this["fieldIRDeliveryDateTo"]));
            }
            set {
                this["fieldIRDeliveryDateTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supplier_CorrespondentBankType")]
        public string fieldIRSupplier_CorrespondentBankType {
            get {
                return ((string)(this["fieldIRSupplier_CorrespondentBankType"]));
            }
            set {
                this["fieldIRSupplier_CorrespondentBankType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Receiver_email")]
        public string fieldIRReceiver_email {
            get {
                return ((string)(this["fieldIRReceiver_email"]));
            }
            set {
                this["fieldIRReceiver_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LineItems")]
        public string fieldIRLineItems {
            get {
                return ((string)(this["fieldIRLineItems"]));
            }
            set {
                this["fieldIRLineItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_PO_Number")]
        public string fieldIRPosition_PO_Number {
            get {
                return ((string)(this["fieldIRPosition_PO_Number"]));
            }
            set {
                this["fieldIRPosition_PO_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Article_Number")]
        public string fieldIRPosition_Article_Number {
            get {
                return ((string)(this["fieldIRPosition_Article_Number"]));
            }
            set {
                this["fieldIRPosition_Article_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Description")]
        public string fieldIRPosition_Description {
            get {
                return ((string)(this["fieldIRPosition_Description"]));
            }
            set {
                this["fieldIRPosition_Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Discount")]
        public string fieldIRPosition_Discount {
            get {
                return ((string)(this["fieldIRPosition_Discount"]));
            }
            set {
                this["fieldIRPosition_Discount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Quantity")]
        public string fieldIRPosition_Quantity {
            get {
                return ((string)(this["fieldIRPosition_Quantity"]));
            }
            set {
                this["fieldIRPosition_Quantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Unit")]
        public string fieldIRPosition_Unit {
            get {
                return ((string)(this["fieldIRPosition_Unit"]));
            }
            set {
                this["fieldIRPosition_Unit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_UnitPrice")]
        public string fieldIRPosition_UnitPrice {
            get {
                return ((string)(this["fieldIRPosition_UnitPrice"]));
            }
            set {
                this["fieldIRPosition_UnitPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_LineTotal")]
        public string fieldIRPosition_LineTotal {
            get {
                return ((string)(this["fieldIRPosition_LineTotal"]));
            }
            set {
                this["fieldIRPosition_LineTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_DeliveryNoteNo")]
        public string fieldIRPosition_DeliveryNoteNo {
            get {
                return ((string)(this["fieldIRPosition_DeliveryNoteNo"]));
            }
            set {
                this["fieldIRPosition_DeliveryNoteNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_POPos")]
        public string fieldIRPosition_POPos {
            get {
                return ((string)(this["fieldIRPosition_POPos"]));
            }
            set {
                this["fieldIRPosition_POPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_VAT")]
        public string fieldIRPosition_VAT {
            get {
                return ((string)(this["fieldIRPosition_VAT"]));
            }
            set {
                this["fieldIRPosition_VAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_AccountIdentifier")]
        public string fieldIRPosition_AccountIdentifier {
            get {
                return ((string)(this["fieldIRPosition_AccountIdentifier"]));
            }
            set {
                this["fieldIRPosition_AccountIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Costcenter")]
        public string fieldIRPosition_Costcenter {
            get {
                return ((string)(this["fieldIRPosition_Costcenter"]));
            }
            set {
                this["fieldIRPosition_Costcenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_AccountNo")]
        public string fieldIRPosition_AccountNo {
            get {
                return ((string)(this["fieldIRPosition_AccountNo"]));
            }
            set {
                this["fieldIRPosition_AccountNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VatItems")]
        public string fieldIRVatItems {
            get {
                return ((string)(this["fieldIRVatItems"]));
            }
            set {
                this["fieldIRVatItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vat_Vat")]
        public string fieldIRVat_Vat {
            get {
                return ((string)(this["fieldIRVat_Vat"]));
            }
            set {
                this["fieldIRVat_Vat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vat_VatAmount")]
        public string fieldIRVat_VatAmount {
            get {
                return ((string)(this["fieldIRVat_VatAmount"]));
            }
            set {
                this["fieldIRVat_VatAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vat_NetAmount")]
        public string fieldIRVat_NetAmount {
            get {
                return ((string)(this["fieldIRVat_NetAmount"]));
            }
            set {
                this["fieldIRVat_NetAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LineItems_MM")]
        public string fieldIRLineItems_MM {
            get {
                return ((string)(this["fieldIRLineItems_MM"]));
            }
            set {
                this["fieldIRLineItems_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_PO_Number_MM")]
        public string fieldIRPosition_PO_Number_MM {
            get {
                return ((string)(this["fieldIRPosition_PO_Number_MM"]));
            }
            set {
                this["fieldIRPosition_PO_Number_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Article_Number_MM")]
        public string fieldIRPosition_Article_Number_MM {
            get {
                return ((string)(this["fieldIRPosition_Article_Number_MM"]));
            }
            set {
                this["fieldIRPosition_Article_Number_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Description_MM")]
        public string fieldIRPosition_Description_MM {
            get {
                return ((string)(this["fieldIRPosition_Description_MM"]));
            }
            set {
                this["fieldIRPosition_Description_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Discount_MM")]
        public string fieldIRPosition_Discount_MM {
            get {
                return ((string)(this["fieldIRPosition_Discount_MM"]));
            }
            set {
                this["fieldIRPosition_Discount_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Quantity_MM")]
        public string fieldIRPosition_Quantity_MM {
            get {
                return ((string)(this["fieldIRPosition_Quantity_MM"]));
            }
            set {
                this["fieldIRPosition_Quantity_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Unit_MM")]
        public string fieldIRPosition_Unit_MM {
            get {
                return ((string)(this["fieldIRPosition_Unit_MM"]));
            }
            set {
                this["fieldIRPosition_Unit_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_UnitPrice_MM")]
        public string fieldIRPosition_UnitPrice_MM {
            get {
                return ((string)(this["fieldIRPosition_UnitPrice_MM"]));
            }
            set {
                this["fieldIRPosition_UnitPrice_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_LineTotal_MM")]
        public string fieldIRPosition_LineTotal_MM {
            get {
                return ((string)(this["fieldIRPosition_LineTotal_MM"]));
            }
            set {
                this["fieldIRPosition_LineTotal_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_DeliveryNoteNo_MM")]
        public string fieldIRPosition_DeliveryNoteNo_MM {
            get {
                return ((string)(this["fieldIRPosition_DeliveryNoteNo_MM"]));
            }
            set {
                this["fieldIRPosition_DeliveryNoteNo_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_POPos_MM")]
        public string fieldIRPosition_POPos_MM {
            get {
                return ((string)(this["fieldIRPosition_POPos_MM"]));
            }
            set {
                this["fieldIRPosition_POPos_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_VAT_MM")]
        public string fieldIRPosition_VAT_MM {
            get {
                return ((string)(this["fieldIRPosition_VAT_MM"]));
            }
            set {
                this["fieldIRPosition_VAT_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LineItems_FI")]
        public string fieldIRLineItems_FI {
            get {
                return ((string)(this["fieldIRLineItems_FI"]));
            }
            set {
                this["fieldIRLineItems_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Description_FI")]
        public string fieldIRPosition_Description_FI {
            get {
                return ((string)(this["fieldIRPosition_Description_FI"]));
            }
            set {
                this["fieldIRPosition_Description_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Discount_FI")]
        public string fieldIRPosition_Discount_FI {
            get {
                return ((string)(this["fieldIRPosition_Discount_FI"]));
            }
            set {
                this["fieldIRPosition_Discount_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Quantity_FI")]
        public string fieldIRPosition_Quantity_FI {
            get {
                return ((string)(this["fieldIRPosition_Quantity_FI"]));
            }
            set {
                this["fieldIRPosition_Quantity_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Unit_FI")]
        public string fieldIRPosition_Unit_FI {
            get {
                return ((string)(this["fieldIRPosition_Unit_FI"]));
            }
            set {
                this["fieldIRPosition_Unit_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_UnitPrice_FI")]
        public string fieldIRPosition_UnitPrice_FI {
            get {
                return ((string)(this["fieldIRPosition_UnitPrice_FI"]));
            }
            set {
                this["fieldIRPosition_UnitPrice_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_LineTotal_FI")]
        public string fieldIRPosition_LineTotal_FI {
            get {
                return ((string)(this["fieldIRPosition_LineTotal_FI"]));
            }
            set {
                this["fieldIRPosition_LineTotal_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_AccountIdentifier_FI")]
        public string fieldIRPosition_AccountIdentifier_FI {
            get {
                return ((string)(this["fieldIRPosition_AccountIdentifier_FI"]));
            }
            set {
                this["fieldIRPosition_AccountIdentifier_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_Costcenter_FI")]
        public string fieldIRPosition_Costcenter_FI {
            get {
                return ((string)(this["fieldIRPosition_Costcenter_FI"]));
            }
            set {
                this["fieldIRPosition_Costcenter_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Position_AccountNo_FI")]
        public string fieldIRPosition_AccountNo_FI {
            get {
                return ((string)(this["fieldIRPosition_AccountNo_FI"]));
            }
            set {
                this["fieldIRPosition_AccountNo_FI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invoice_Number|PO_Number|Total_Amount|Supplier_Name|Net_Amount1|VAT_Amount1|VAT1|" +
            "Invoice_Date")]
        public string fieldsToCheck {
            get {
                return ((string)(this["fieldsToCheck"]));
            }
            set {
                this["fieldsToCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Completion|FreeProcess")]
        public string stationsToCheckForFields {
            get {
                return ((string)(this["stationsToCheckForFields"]));
            }
            set {
                this["stationsToCheckForFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("supplierportaluser")]
        public string imgUserName {
            get {
                return ((string)(this["imgUserName"]));
            }
            set {
                this["imgUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e7low5!!")]
        public string imgPwd {
            get {
                return ((string)(this["imgPwd"]));
            }
            set {
                this["imgPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images")]
        public string imgFolder {
            get {
                return ((string)(this["imgFolder"]));
            }
            set {
                this["imgFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/images_receive")]
        public string imgReceive {
            get {
                return ((string)(this["imgReceive"]));
            }
            set {
                this["imgReceive"] = value;
            }
        }
    }
}
